### ISSUE TITLE
lang.ArrayIndexOutOfBoundsException when loading image

### ISSUE THREAD

**Issue by Martijnpold** [InventivetalentDev/MapManager#10]
## What steps will reproduce the problem?  
1. Download image: http://puu.sh/vyRuH/aba24f8734.png
2. Code: https://pastebin.com/GCv4y7Ph
3. Enter a value in the method, should cut out the image at the index of the block provided and put it on the map.

## What were you expecting to happen? What happened instead?  
I am trying to get part of an image and display that on a map, received an error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.3.4-SNAPSHOT

## What Spigot version are you using? *Type /version*  
version 1.10-R0.1-SNAPSHOT

## What plugins ae you using? *Type /plugins*  
Custom plugins, no official ones

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/tkb45uUD

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No previous versions or bungeecord, just plain Spigot with the version above.

**Comment by InventivetalentDev** [comment]
The API expects an image to be at least 128 by 128 pixels (size of one map). 
You can either scale up your base 16x16 image, or place it on a 128x128 background if you' like to keep the original size.
