### ISSUE TITLE
MapManager + AnimatedFrames ---> Vanilla maps break every restart

### ISSUE THREAD

**Issue by Dragoboss** [InventivetalentDev/MapManager#12]
## What steps will reproduce the problem?  
1. Fresh install MapManager + AnimatedFrames
2. Create some non-animated banners, in my case at our /spawn
3. Craft a normal (player) map
4. Right click the map, it will create a map with the image of the spawn banners.
I have to cycle through all of the images of all the banners at /spawn before regular maps start working again.

## What were you expecting to happen? What happened instead?  
Well the idea would be that it would skip the map-ids that are occupied by AnimatedFrames, so that when a player creates a normal, AKA vanilla map, he gets an actual map and not a part of the banners that are on display at spawn.

It would also be fine if I only had to create the occupied map-ids once and it then working forever afterwards, but currently I have to do this every time we restart the server (so once every 24 hours).

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;* 
MapManager 1.3.4-SNAPSHOT
AnimatedFrames 4.4.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Spigot 1.10.2-R0.1
git-spigot-de459a2-51263e9

## What plugins are you using? *Type /plugins*  
A whole load, but none of the other plugins affects map behavior.
I am happy to provide a list of plugins through a private means but do not wish to publicly post them.

This also happens when these two plugins are the only ones installed.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
Not Applicable

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Not Applicable

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using BungeeCord but these plugins are installed on only one of the two playable servers, and not through the cord.

**Comment by Dragoboss** [comment]
Just for clarification:

If there is a way to configure this usage, I have not found it. I have tried multiple combinations of the settings provided in MapManager. I've reset the full idcounts and map .dat files multiple times to see if that was the cause (maps work right after until I recreate the banners at /spawn).

If this was a feature that was never supposed to work, I understand, but could you look into finding a way to provide this, still?

Normally I'd be happy to have a look myself but your programming is a little above my pay-grade so to speak.

**Comment by Fonzee9** [comment]
Same problem

**Comment by Wolf2323** [comment]
Same problem

**Comment by colinrgodsey** [comment]
same
