### ISSUE TITLE
Update Method is a bit slow // Fluent animations

### ISSUE THREAD

**Issue by DevLeoko** [InventivetalentDev/MapManager#18]
## What steps will reproduce the problem?  
I'm setting up a MultiMapWrapper/Controller and then try to update the image every two ticks.
But instead of having a delay of 0.05 sec I'm having a delay of around 0.25 sec which is caused by the https://github.com/InventivetalentDev/MapManager/blob/1a01eb1d47948b21c7f412d708b5c810b81e7078/src/org/inventivetalent/mapmanager/MultiMapWrapper.java#L87 Method

Is there any other way to update a map faster? As the Nyan-Cat example on the AnimatedFrames Spigot page seems to be a lot more fluent. Also, I'm not able to use a GIF file because the updates are dynamic.

Thanks for reading and any help in advance :)
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
MapManager -> 1.4.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Spigot 1.8.6 R0.1 SNAPSHOT

## What plugins are you using? *Type /plugins*  
MapManager, PacketListenerAPI, My Plugin

**Comment by InventivetalentDev** [comment]
That's because AnimatedFrames works differently. It pre-generates the images and then changes the map items in the item frames.
There's no other way to achieve such smooth animations, unfortunately. 

Feel free to take a look at the AnimatedFrames source :) https://github.com/InventivetalentDev/AnimatedFrames

**Comment by DevLeoko** [comment]
Okay I understand, thanks for the fast response. 
But if I have let's say 5 different images. Cloud I pre-generate them all with the MapManager API and then dynamically show them to the player?
If yes, how would I do that, which methods pre-generates them?

Also, a second question where I have a bad feeling that I can already guess the answer :D
If I have dynamic content in the image and there are about 300 possibilities how the final image could look. Would it kill the performance of the server or client if I would pre-generate them all so I can dynamically change them? ^^

**Comment by InventivetalentDev** [comment]
Yeah, you can take a look at the code in https://github.com/InventivetalentDev/AnimatedFrames/blob/master/src/main/java/org/inventivetalent/animatedframes/AnimatedFrame.java#L124 - basically, just generate the wrappers for your individual images and then display them in the frames when you need them.
But displaying dynamic content at a fast speed is pretty much impossible in Minecraft :/

**Comment by DevLeoko** [comment]
Okay thank you a lot, this solved my issue :) Prerendering multiple options makes it possible to show dynamic content to the user at a high speed.
