### ISSUE TITLE
entityIdMatrix is accessed incorrectly.

### ISSUE THREAD

**Issue by Blutkrone** [InventivetalentDev/MapManager#19]
See line 118 (MultiMapWrapper.java)

> 
> 		@Override
> 		public void showInFrames(Player player, int[][] entityIdMatrix) {
> 			for (int x = 0; x < entityIdMatrix.length; x++) {
> 				for (int y = 0; y < entityIdMatrix[x].length; y++) {
> 					wrapperMatrix[y][x].getController().showInFrame(player, entityIdMatrix**[x][wrapperMatrix.length - 1 - y]**);
> 				}
> 			}
> }
>

You forgot to invert the axis here, nor do you mention it in the javadocs (The entityIdMatrix is accessing in a wrong manner.)

**Comment by InventivetalentDev** [comment]
This method is used by the AnimatedFrames plugin (see [AnimatedFrame#214](https://github.com/InventivetalentDev/AnimatedFrames/blob/master/src/main/java/org/inventivetalent/animatedframes/AnimatedFrame.java#L214)) and it works correctly there.
