### ISSUE TITLE
Comman /mm is main command for MythicMobs

### ISSUE THREAD

**Issue by Fortepsai** [InventivetalentDev/MapManager#21]
Please create the different alias for this command, your plugin is way not so used 
as a MythicMobs . This is really not good fo me, i have a RPG server and this plugin is needed for animated frames .

**Comment by InventivetalentDev** [comment]
ouch :c

**Comment by marcostijerina** [comment]
Thank you for catching that and fixing that...I'll undo my rigged fix.
