### ISSUE TITLE
Is unwrapImage(MapWrapper wrapper); needed?

### ISSUE THREAD

**Issue by DevLeoko** [InventivetalentDev/MapManager#22]
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.4.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.8.8 R0.1 SNAPSHOT

## What plugins are you using? *Type /plugins*  
MapManager, ProtocolLib, My own Plugin

## My Issue
- I had some updating issues (long loading times) when there are many players online
- I got some *OutOfMemory* and *GC overhead limit exceeded* errors (not 100% sure if they are related to mapmanager)
- I have an issue when players reconnect, the Frames are not reassigned properly in the right order or are not displayed to the user at all

So I thought that a possible cause for that may be that old data gets stacked and leads to the issues explained above as I make a lot of map updates and basically just overwrite the old data. I searched through the API and found the https://github.com/InventivetalentDev/MapManager/blob/bb9f177d257f3e1801cadca79a925f17257c79a3/src/org/inventivetalent/mapmanager/manager/MapManager.java#L55 method and wanted to ask what exactly this method does and when/if it should be called? Also, do you know anything else that may solve my issues from above?

**Comment by InventivetalentDev** [comment]
The [implementation of unwrapImage](https://github.com/InventivetalentDev/MapManager/blob/1a01eb1d47948b21c7f412d708b5c810b81e7078/src/org/inventivetalent/mapmanager/DefaultMapManager.java#L54) basically aborts any data that's queued from being sent to the player and the wrapper stops being managed by the plugin. So you'll probably want to call that method every time you're done using a specific wrapper and are ready to "destroy" it.

**Comment by DevLeoko** [comment]
Okay, I'm doing that now. I yet can't say for sure but I think it reduced the memory leaks 👍 

But there is still one more bug I have.
Sometimes when generating a new image and displaying it to a user at a point where an old image has previously been this occurs: https://image.prntscr.com/image/Pxd2n37sRv21Q6Mdl_utDQ.png

**Comment by InventivetalentDev** [comment]
Unfortunately, that occurs when all the map ids are used up. If you're properly unwrapping your old images, it should catch up and fix the image by itself, though.

**Comment by DevLeoko** [comment]
I'm using `mapManager.unwrapImage(wrapper)` where wrapper is an instance of MultiMapWrapper
So it should unwrapp the old images properly. Also this happens already after the first image change which makes it unlikly that all IDs are already used as I think I have 30k+ IDs.

This is one of the few major issues we need to solve before we release our network. Cloud you add me on discord for a more efficient communication? :) Leoko#4115

**Comment by DevLeoko** [comment]
Bump. Please help
