### ISSUE TITLE
java.lang.NoSuchFieldError: v1_13_R1

### ISSUE THREAD

**Issue by SpraxDev** [InventivetalentDev/MapManager#23]
## What steps will reproduce the problem?  
It is thrown only one time after the server started. I can't reproduce it but I use Sentry to automatically log all exceptions.

## What were you expecting to happen? What happened instead?
I can't reproduce the exception... I would think my Maps in the item frames would not load for a specific player but I can't check that...

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*
1.5.2-SNAPSHOT

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins ae you using? *Type /plugins*
`Plugins (24): AAC, AdvancedDevUtils-CBN, AdvancedDevUtils-Spigot, AnimatedFrames, AntiLaby, BetterChairs, BossBarAPI, CherryEssentials, CommandSync, EmptyWorldGenerator, ErrorSink, LobbySystem, LuckPerms, MapManager, NoteBlockAPI, OnlyProxyJoin, PacketListenerApi, Plan, ProtocolLib, ServerHolograms, ServerSigns, TeleportAreas, ViaVersion, WorldBorder`

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
https://pastebin.com/zsh1FSHa

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using BungeeCord. I did not get the exception in previous versions but it happens irregularly.

**Comment by InventivetalentDev** [comment]
Are there any issues with MapManager/AnimatedFrames after this, or do they work as intended anyway?

**Comment by SpraxDev** [comment]
I could not see any other errors or mistakes while displaying the animated frames

**Comment by SpraxDev** [comment]
Got some more information now. The bug (?) does not affect images being displayed. I've updated to MapManager v1.7.0-SNAPSHOT and AnimatedFrames v4.10.0-SNAPSHOT.

The stack trace is not visible in lates.log or in the console. But it is reported to sentry.io. I am using 'ErrorSink' to collect StackTraces and error-messages and send them to sentry.io. According to the stack trace, it is a bug (?) in AnimatedFrames.

It is kind of annoying but I don't know if it affects performance or animated images/maps.

Screenshot: https://screenshots.firefox.com/UH4I3xxuGQYhMZCH/sentry.io

Last seen (From the screenshot): November 18 2018 19:39:14 CET

Stacktrace (From the screenshot):
```
java.lang.NoSuchFieldError: v1_13_R1
    at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:298)
    at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:219)
    at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:224)
    at org.inventivetalent.mapmanager.MultiMapWrapper$1.showInFrames(MultiMapWrapper.java:122)
    at org.inventivetalent.animatedframes.AnimatedFrame.displayCurrentFrame(AnimatedFrame.java:290)
    at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:268)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by InventivetalentDev** [comment]
Could you please check if PacketListenerAPI is also up-to-date? This appears to be caused by an outdated version of ReflectionHelper packaged in one of the plugins.

**Comment by SpraxDev** [comment]
I am using PacketListenerAPI v3.7.1. And re-uploading the latest file from GitHub didn't change anything.
I am using Spigot 1.8.8 ( CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) )
