### ISSUE TITLE
MapManager bug with Spigot 11.1 

### ISSUE THREAD

**Issue by Shaked** [InventivetalentDev/MapManager#4]
## What steps will reproduce the problem?  
1. Generate a new frame /afg
2. Create a new animated frame /afcreate name https://media2.giphy.com/media/l2R0aKwejYr8ycKAg/200_s.gif
3. Move around it\wait

## What were you expecting to happen? What happened instead?
  Game should work, instead the game crashes. 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*
  1.2.0

## What Spigot version are you using? *Type /version*
  1.11

## What plugins ae you using? *Type /plugins*
  Animated Frames 4.3.3
  MapManager 1.2.0
  PacketListenerAPI 3.4.4

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
http://pastebin.com/sN9mY4kv  

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
http://pastebin.com/fL59KJNE

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I have debugged MapManager and Spigot 11.1, I have also tried to update the dependencies. It seems that there is a problem with `PacketPlayOutEntityMetadata` although I might be wrong. 

Any ideas? I would be happy to help fixing it but kinda stuck. 

Thank you
Shaked

**Comment by InventivetalentDev** [comment]
Should be fixed.

**Comment by Shaked** [comment]
Hey @InventivetalentDev, 

I forgot to update that I have found the problem and fixed it by doing the following code change in `DefaultMapWrapper.java`: 

```
} else if (Minecraft.VERSION.olderThan(Minecraft.Version.v1_11_R1)){
	Object dataWatcherObject = EntityItemFrameFieldResolver.resolve("c").get(null);
	Object dataWatcherItem = DataWatcherItemConstructorResolver.resolveFirstConstructor().newInstance(dataWatcherObject, com.google.common.base.Optional.fromNullable(craftItemStack));

	list.add(dataWatcherItem);
} else {
	Object dataWatcherObject = EntityItemFrameFieldResolver.resolve("c").get(null);
	if (craftItemStack != null) {
		Object dataWatcherItem = DataWatcherItemConstructorResolver.resolveFirstConstructor().newInstance(dataWatcherObject, craftItemStack);
		list.add(dataWatcherItem);
	}
}
```

I hope it helps,
Thank you for your update!
Shaked
