### ISSUE TITLE
player crashing on 1.14 on entity interact and block picking

### ISSUE THREAD

**Issue by LadyHaley** [InventivetalentDev/MapManager#40]
## What steps will reproduce the problem?  
1. hit an entity on my version of spigot with the plugin installed
2. 
3. 

## What were you expecting to happen? What happened instead?  
not crashing
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
https://i.imgur.com/WTm33lW.png
## What Spigot version are you using? *Type /version*  
https://i.imgur.com/WTm33lW.png
## What plugins are you using? *Type /plugins*  
https://i.imgur.com/FfEI0bN.png
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
[2019-09-03-7.log](https://github.com/InventivetalentDev/MapManager/files/3567747/2019-09-03-7.log)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
On entity interact
https://i.imgur.com/m87enmi.png
On block pick in creative
https://i.imgur.com/v6FQW1M.png

**Comment by InventivetalentDev** [comment]
Please enable `debug` in `server.properties` and `settings.debug` in `spigot.yml` and post the log when it occurs again, that will have some more info.

**Comment by LadyHaley** [comment]
Ill get on that!!

**Comment by LadyHaley** [comment]
Here you go
https://pastebin.com/5rWbn56j

I was not able to replicate the pick block issue

**Comment by InventivetalentDev** [comment]
Looks like there's a conflict with some old code, though I can't see any outdated plugins of mine in the log.

**Comment by LadyHaley** [comment]
I am unable to do any further testing for a while but I can look into it when I have the chance, let me know if you happen to figure it out in the mean time

**Comment by LadyHaley** [comment]
I have not been able to do any testing as of yet, any progress with this on your end?
