### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by stijnb1234** [InventivetalentDev/MapManager#42]
I'm trying to get an image on a ItemFrame with this API, but the image isn't shown.

My code:
```java
//location is the itemframe location and image is the image
public static void makeArt(Location location, BufferedImage image) {
    MapWrapper wrapper = Main.getMapManager().wrapImage(image);
    MapController controller = wrapper.getController();
    for (Player p : Bukkit.getOnlinePlayers()) {
        controller.addViewer(p);
        controller.sendContent(p);
    }

    getSafeFrame(location).thenAccept(frame -> {
        if (frame == null) return;
        for (Player p : Bukkit.getOnlinePlayers()) {
            controller.showInFrame(p, frame);
        }
    });
}

private static ItemFrame getFrame(@NotNull Location loc) {
    ItemFrame frame = null;
    if (loc.getChunk().getEntities().length != 0) {
        for (Entity e: loc.getChunk().getEntities()) {
            if (MainUtil.locationEquals(e.getLocation(), loc)) {
                if (e instanceof ItemFrame) {
                    frame = (ItemFrame) e;
                    break;
                }
            }
        }
    }
    return frame;
}

//Using a CompletableFuture becuase it's runned async
@NotNull
private static CompletableFuture <ItemFrame> getSafeFrame(@NotNull Location location) {
    CompletableFuture <ItemFrame> cf = new CompletableFuture < > ();

    Bukkit.getScheduler().runTask(Main.getInstance(), () -> cf.complete(getFrame(location)));

    return cf;
}
```

## What steps will reproduce the problem?  
1. Trying to use the API
2. Can't get a BufferedImage onto a frame

## What were you expecting to happen? What happened instead?  
The image that gets displayed on the ItemFrame.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
MapManager v1.7.4-SNAPSHOT
PacketListenerApi v3.7.5-SNAPSHOT

## What Spigot version are you using? *Type /version*  
git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) -> Latest build

## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/27051051/71781634-475a6c00-2fd1-11ea-8141-a486e2c3aced.png)

**Comment by stijnb1234** [comment]
Hello? Still needed.

**Comment by InventivetalentDev** [comment]
When are you running your code? Might just be a case of stuff being sent too soon.

**Comment by stijnb1234** [comment]
How do you mean too soon?

**Comment by stijnb1234** [comment]
Hello?

**Comment by InventivetalentDev** [comment]
> When are you running your code?

**Comment by stijnb1234** [comment]
Oh, I'm sorry. Didn't read that.

The player can run a command, `/af take <BoardName> <Username>` and then the plugin will make an BufferedImage of the player with a background and put it on the board at the location in my code.

But is there anything wrong with the code above, or not? Because the itemframe is empty, and if I first put a Map in the itemframe and then run the code, I can see the image for 1 millisecond and then it's away.

**Comment by InventivetalentDev** [comment]
Your code looks fine from what I can tell.  
But the fact that you can see the image for a brief moment makes me think there's something interfering with MapManager's packet handling.  

Though you could try passing `true` as the third argument to `showInFrame` to force the display even if there's no map in the item frame.

**Comment by stijnb1234** [comment]
Okay, I will try that.

**Comment by stijnb1234** [comment]
Okay, I've got something now.

But the image is corrupted. The image I'm sending into it is not corrupted, I'm sure (converted it to base64 and it's normal).

![image](https://user-images.githubusercontent.com/27051051/72559752-d0ad5080-38a5-11ea-91ad-dd81239ef048.png)

Do you know how to fix this?

**Comment by InventivetalentDev** [comment]
Hmm, that's weird. 
What are the image's dimensions and format?

**Comment by stijnb1234** [comment]
The image is 150x150 and the format is PNG.

**Comment by stijnb1234** [comment]
The image dimensions were wrong. I changed them to 128x128 and now it's working. Thanks!

**Comment by stijnb1234** [comment]
I get this error when I get the image from the frame and put it in my hand:

https://paste.themelvin.nl/D6mHzK

**Comment by InventivetalentDev** [comment]
Something I gotta fix.
