### ISSUE TITLE
java.lang.IllegalStateException: MapInteractEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by Ghost-chu** [InventivetalentDev/MapManager#44]
## What steps will reproduce the problem?  
1. Interact a map create by AnimatedFrames
## What were you expecting to happen? What happened instead?  
Console throw exceptions

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
MapManager version 1.7.4-SNAPSHOT
## What Spigot version are you using? *Type /version*  
This server is running Paper version git-Paper-35 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
## What plugins ae you using? *Type /plugins*  
Plugins (109): AdvancedReplay*, AFKTitle*, AkkariinTerminal*, AlertMineWorld, AncientGates, AnimatedFrames*, AntiEnderPortalBreaker, BBSToper*, BeehiveInfo, BeeHivesTrees, BorderProtect, BossShopPro, CaulCrafting*, Chair, ChatReplay, ChineseCommand*, Citizens, CitizensCMD, CmdConfirm*, ColorAnvil*, ColoredBooks*, CommandNotifier, Confiscate, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CraftBook, CustomJukeBox, EndPortalBreakFix*, EntityDetection, EntityTrackerFixer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExtendViewDistance*, F3Name, FakeSeed, FixMyData*, ForceResourcepacks, GCore, GreenFingers, HamsterEcoHelper, HeadDropsSS, HolographicDisplays, HopperFilter, HorseArmor, HorseArmorEnchants, IllegalStack, InventoryRollback, JetsMinions*, KickIdlePlayer, LangUtils, Lift, LimitPillagers, LiteBans, LockettePro, Lores*, LuckPerms, MapManager*, MaxRepairCost, mcMMO, MineCalendar, MineSecure*, MineSync*, MobFarmManager, MoreCompost, Multiverse-Core, MyPet, MyWarp, NewbieProtection, NMSCatAPI, NyaaCore, NyaaUtils, OpenInv, ourtown, PacketEventCatAPI*, PacketListenerApi*, PetMaster, PlaceholderAPI, Plan, PlayerReport*, PlayTimeTracker, PlugMan*, ProtocolLib, PublicCrafters, QuestCreator, QuickShop, ravager-anti-grief, RideMe-Plus*, RPGItems, RuleQuizzer, SafetyReboot*, Shopkeepers, SmoothSleep, spark, StarGate, SuperVanish, TitleManager*, TouchscreenHolograms, Vault, VillagerOptimiser, WebFrames*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, YouAreNotLostConnection*
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://paste.ubuntu.com/p/xvwCStR9M5/
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It happend on AnimateFrames before, i forked it and fix it by myself, and now, MapManager starting throwing....
This changes is spigot changes on 1.15, async event only can call on offmain therad, and sync is same.

**Comment by stijnb1234** [comment]
Fixed in [this commit](https://github.com/InventivetalentDev/MapManager/commit/053e196e417c54ecc68aefa2fc96a9c2c1d2803d)
