### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid map dimension: 11

### ISSUE THREAD

**Issue by Dymeth** [InventivetalentDev/MapManager#47]
When the plugin starts, a large number of messages are displayed like:
[MapManager] Adding new Map # 154 to occupied IDs.
[MapManager] Adding new Map # 155 to occupied IDs.
...
[MapManager] Adding new Map # 245 to occupied IDs.
[MapManager] Found 227 occupied IDs.

Some maps throw exceptions: https://pastebin.com/raw/1VqPQ3Wu
A total of about 18-19 errors (245 - 227)

Perhaps the problem is that today the server upgraded from version 1.13.2 to version 1.14.4, and then immediately to 1.15.2

It would be great:
a) To fix loading errors
b) To get rid of spam in the console

Versions:
> about PacketListenerAPI
PacketListenerApi version 3.7.5-SNAPSHOT
Author: inventivetalent

> about MapManager
MapManager version 1.7.7-SNAPSHOT
Author: inventivetalent

> about AnimatedFrames
AnimatedFrames version 4.11.4-SNAPSHOT
Author: inventivetalent

> about
This server is running Paper version git-Paper-79 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-243 (MC: 1.14.4)
You are running the latest version

**Comment by stijnb1234** [comment]
```
[MapManager] Adding new Map # 154 to occupied IDs.
[MapManager] Adding new Map # 155 to occupied IDs.
[...]
```

These messages are not errors. If you have a large number of map IDs in use, it will load them all.
So I would recommend to the Developer to either reduce them (loaded 1-10...) or disable them.

**Comment by stijnb1234** [comment]
Maybe try to update your Paper version?

https://papermc.io/downloads

Build 121 is available.

**Comment by Dymeth** [comment]
> Maybe try to update your Paper version?
> 
> https://papermc.io/downloads
> 
> Build 121 is available.

Similar warnings on git-Paper-126 (MC: 1.15.2) and same exceptions: https://pastebin.com/raw/shFLkHwY

**Comment by InventivetalentDev** [comment]
Looks like this is caused by the plugin trying to load a map that was created in a dimension (world) that doesn't exist. Did you maybe delete any worlds before this error occurred?

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/MapManager/commit/35a1737192551e6fa28757c78908f3ac290686c0

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/MapManager/issues/51

**Comment by InventivetalentDev** [comment]
Please try deleting the respective files in the `<worldname>/data/` directories.  
E.g. if the error message says `Error loading saved data: map_2991` delete `map_2991.dat` in that directory. (Obviously create a backup first)

**Comment by Dymeth** [comment]
> Looks like this is caused by the plugin trying to load a map that was created in a dimension (world) that doesn't exist. Did you maybe delete any worlds before this error occurred?

It is possible that this could happen, but I can’t be sure of it.

> Please try deleting the respective files in the `<worldname>/data/` directories.
> E.g. if the error message says `Error loading saved data: map_2991` delete `map_2991.dat` in that directory. (Obviously create a backup first)

It helped get rid of errors, thanks!
Should I close the issue?
