### ISSUE TITLE
Not enabling

### ISSUE THREAD

**Issue by biefbink** [InventivetalentDev/MapManager#5]
## What steps will reproduce the problem?  
1. 
2. 
3. 

## What were you expecting to happen? What happened instead?  
To get it enabled, they are both disabled (animatedframes and mapmanager)
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Mapmanager: 1.3.2-SNAPSHOT
Animated frames: 4.4.1-SNAPSHOT
## What Spigot version are you using? *Type /version*  
http://imgur.com/a/3ZFsO
## What plugins ae you using? *Type /plugins*  
http://imgur.com/a/S0Pm7
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
http://imgur.com/a/cseQ1
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Not using bungeecord

**Comment by InventivetalentDev** [comment]
Please post the **full** log and use a site like [hastebin](http://hastebin.com/) for it.

**Comment by InventivetalentDev** [comment]
Btw, it's showing a message that you're missing PacketListenerAPI, so make sure you have that latest version installed.

**Comment by biefbink** [comment]
https://hastebin.com/lijodolebi.sql
My console log, my plugins: http://imgur.com/a/MwaIR as you might see, there is no PacketListenerAPI folder, PLEASE HELP!

**Comment by InventivetalentDev** [comment]
Not all plugins are supposed to generate a plugin folder, including PacketListenerAPI.

**Comment by InventivetalentDev** [comment]
Please install the latest version of PacketListenerAPI.
