### ISSUE TITLE
Treasure maps show maps setup by AnimatedFrames (Issue with this API, or the other plugin?)

### ISSUE THREAD

**Issue by thefear900** [InventivetalentDev/MapManager#55]
## What steps will reproduce the problem?  
1. Add an image to item frames via AnimatedFrames (one JPG setup across 2 item frames
2. Random Treasure Maps found in the world are the item frame pictures
3. 

## What were you expecting to happen? What happened instead?  
Was expecting normal treasure maps to be normal treasure maps
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.5-snapshot
## What Spigot version are you using? *Type /version*  
Paper build 184
## What plugins are you using? *Type /plugins*  
AnimatedFrames4.II.5-SNAPSHOTjar
BKCommonLibjar
chunkmasterjar
ConsoleSpamFix-I.8.2jar
Coreprotect-2.18.I jar
DeathCoordinatesjar
DiscordSRV-8uild-1.19D-SNAPSHOT-1...
DKLibjar
Dynmap-3D-beta- ID-spigotjar
EssentialsX-2.17.2.5gjar
EssentialsXChat-2.17.2.5gjar
EssentialsXGeoIP-2.17.2.5gjar
LuckPerms-8ukkit-5.O.104jar
MapManager_v1.78-SNAPSHOTjar
Multiverse-Core-4.I.Ojar
Multiverse-PotaIs-4.I .O.jar
NoteBlockAPI-I .4Ajar
NoteBlockPIayerjar
Openlnv.jar
PacketListenerAPI_v3.7.6-SNAPSHOTjar
Plan-5.I-buiId-497.jar
Play Time-I .14jar
PlugManjar
RandomTeIeportjar
Signportalsjar
SpigotPing_v2.5jar
TAB v2.73.jar
Tree* Feller+ I .103jar
Vaultjar
worldedit-bukkit-7.I.O (I)jar
WorldEditSeIectionVisuaIizer-2.OAjar
worldguard-bukkit-7.O.2jar

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
N/A
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
N/A
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Is this an issue with this API, or is it a problem solely with AnimatedFrames?

**Comment by InventivetalentDev** [comment]
are you allowing vanilla maps in the config?

**Comment by thefear900** [comment]
I have left the config as default, allowvanilla is set to true. I did not set paperspigot to true, however. Would this have affected it?

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 29, 2020 at 2:55, Haylee Schäfer<notifications@github.com> wrote:   


are you allowing vanilla maps in the config?
