### ISSUE TITLE
MapManager Error with Animated Frames

### ISSUE THREAD

**Issue by Herodennis** [InventivetalentDev/MapManager#6]
## What steps will reproduce the problem?  
1. Just starting the Server
2. Got MapManager Error
3. When i use /afcreate Test url, 2nd error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
  1.3.3 Snapshot MapManager
  4.3.3 AnimatedFrames
  3.4.4 PacketListenerAPI
## What Spigot version are you using? *Type /version*  
Spigot-4741400-a1d3777 (MC:1.11.2)
## What plugins ae you using? *Type /plugins*  
  Coreprotect, CratesPlus,BlockParticles,Worldedit,MapManager,Votifier,WorldGuard,FastMaps,Autosaveworld,Mythicdrops,ImageOnMap,React,Changegamemode,PermissonsEX,JoinMessageChanger, MotdManager-Reloaded,SimpleVoteListiner,Vault,MyCommand,MassivCore,MysqlEcoBridge,Essentials,CreativeControl,AnimatedFrames,CreativeGates,bChatManager,MobLoot,ActionHealth,TreasureChest,Citizens,CommandNPC,Bossshop,WorldGuardExtraFlags,TitleManager,MyPet
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
MapManager http://pastebin.com/QYeeUMLM

AnimatedFrames:
Picture: http://fs5.directupload.net/images/170202/t2yymd6h.png
LOG: http://pastebin.com/m5wEKmA7
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I dont use anything else

**Comment by Rocologo** [comment]
Same bug https://github.com/InventivetalentDev/AnimatedFrames/issues/35
