### ISSUE TITLE
Request for slight performance optimization

### ISSUE THREAD

**Issue by stylextv** [InventivetalentDev/MapManager#63]
https://github.com/InventivetalentDev/MapManager/blob/3b8bec1f18ea3dc04ec2725353c30e00198e9b6b/src/org/inventivetalent/mapmanager/MapManagerPlugin.java#L86

When searching through all the possible map ids, looking for vanilla maps, wouldn't it be faster to start at 'Options.FORCED_OFFSET' rather than 0, since when getting a new, free map id you start searching at that offset:

https://github.com/InventivetalentDev/MapManager/blob/3b8bec1f18ea3dc04ec2725353c30e00198e9b6b/src/org/inventivetalent/mapmanager/DefaultMapManager.java#L124

**Comment by InventivetalentDev** [comment]
Yeah, that would probably be a bit faster, but shouldn't make much of a difference since that's just run on startup. 
I also think I'd like to keep it starting at 0, just in case there happen to be any used up maps before the forced-offset.  
Thanks for the suggestion though :)
