### ISSUE TITLE
The showInFrame function don't work

### ISSUE THREAD

**Issue by Caranouga** [InventivetalentDev/MapManager#89]
**Describe the bug**
I got the plugin to work, but when I try to put an image in a frame, nothing happens

**Expected behavior**
It should normaly put the image in the itemframe

**Screenshots**

Code: https://www.toptal.com/developers/hastebin/iqebaneriq.java
Console: https://www.toptal.com/developers/hastebin/cudakoxeya.md
Screen of my setup: https://prnt.sc/EK-dB5Upj-UY

**Additional context**
I've tried to update MapManager so, i've these plugins in the plugin folder: https://prnt.sc/Je5XE6hYW7Wd and this pom.xml https://www.toptal.com/developers/hastebin/ahecuvawig.xml

**Comment by stijnb1234** [comment]
> **Describe the bug** I got the plugin to work, but when I try to put an image in a frame, nothing happens
> 
> **Expected behavior** It should normaly put the image in the itemframe
> 
> **Screenshots**
> 
> Code: https://www.toptal.com/developers/hastebin/iqebaneriq.java Console: https://www.toptal.com/developers/hastebin/cudakoxeya.md Screen of my setup: https://prnt.sc/EK-dB5Upj-UY
> 
> **Additional context** I've tried to update MapManager so, i've these plugins in the plugin folder: https://prnt.sc/Je5XE6hYW7Wd and this pom.xml https://www.toptal.com/developers/hastebin/ahecuvawig.xml

Is your image scaled to 128x128 pixels?

**Comment by Caranouga** [comment]
Yes, my image is 128x128 pixels

**Comment by Caranouga** [comment]
![photo_btm_4 06 07 0](https://user-images.githubusercontent.com/62339171/172827259-35764f61-22b6-4ecd-a634-c415dcb5bf8d.png)
Here is the photo I want to put in the item frame

**Comment by InventivetalentDev** [comment]
when are you calling the #addPhoto method?  
does the image show in hour hand?  
also, maybe try putting a map item into the item frame and holding one in your hand

**Comment by Caranouga** [comment]
I call the addPhoto function when a minecart passes over a sign with traincarts.

I use this function ItemFrameManager.addPhoto(info.getLine(2) //btm, main, photonumber //123456, info.getLine(3) //3000 Used for something else than the picture); 

When I hold a map in my hand, it doesn't matter, it's still a vanilla map, and the map in the itemframe is also a vanilla map

My new setup: https://prnt.sc/dgRy3L-3a0PM


UPDATE: When I hold a map in my hand, it doesn't matter, it's still a vanilla map, but when i create a new map this is not a vanilla map, but a map with my photo

**Comment by Caranouga** [comment]
I tried to put the code from my sign in an order, and it worked! I think there must be a problem with the traincarts and mapmanager signs!

Thanks to all !
