### ISSUE TITLE
ShowInInventory doesn't work and give me an error

### ISSUE THREAD

**Issue by Caranouga** [InventivetalentDev/MapManager#91]
**Describe the bug**
Good evening to all! I'm coming to you because I have a little problem with Map Manager, I have an image and I would like to give this image as a map to a player, but I can't. Can you help me?

Here is the code I have at the moment: https://www.toptal.com/developers/hastebin/eyitenabuz.java

Error: https://www.toptal.com/developers/hastebin/ecuyemuxuc.log

Thanks to you !

**To Reproduce**
1. Do /buyphoto

**Expected behavior**
Normally I am supposed to receive the photo in my inventory, but I don't receive anything and I have an error

**Comment by stijnb1234** [comment]
The latest version does not correctly support all versions, it only works correct for 1.18.

**Comment by Caranouga** [comment]
Hello, thank you for your reply. So from what I understand from your message the latest version (1.8.8-SNAPSHOT) does not support 1.17.1. Is that it? If so how can I get it to work?

**Comment by stijnb1234** [comment]
> Hello, thank you for your reply. So from what I understand from your message the latest version (1.8.8-SNAPSHOT) does not support 1.17.1. Is that it? If so how can I get it to work?

It's not my plugin, but you can try using an older version.

**Comment by Caranouga** [comment]
I've tried to use all of the version that are available (1.8.0-1.8.8) but none of these work

**Comment by stijnb1234** [comment]
> I've tried to use all of the version that are available (1.8.0-1.8.8) but none of these work

You can always give my fork a try:
https://github.com/SBDPlugins/MapReflectionAPI

Maybe you get it working using that.

**Comment by Caranouga** [comment]
I've tried your fork, but i still have a problem. It gives me the map but it doesn't have my picture on it :(. I'll open an issue on your fork ^^ so we can talk about it
